global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MSmartCompute Platform
  - job_name: 'msmartcompute-platform'
    static_configs:
      - targets: ['msmartcompute:8080']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node Exporter (if running)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

# Alerting rules
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Recording rules
rule_files:
  - "msmartcompute_rules.yml" 